name: ms2query
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.18
  - matchms=0.24.1
  - numpy=1.24.4
  - spec2vec=0.8.0
  - h5py=3.10.0
  - pyarrow=14.0.2
  - tensorflow=2.8.4
  - scikit-learn=1.3.2
  - ms2deepscore=0.4.0
  - gensim=4.3.2
  - pandas=2.0.3
  - tqdm=4.66.1
  - matplotlib=3.7.4
  - skl2onnx=1.16.0
  - onnxruntime=1.15.1
  - bump2version=1.0.1
  - isort=5.13.2
  - prospector=1.10.3
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - sphinx=3.5.4
  - sphinx-rtd-theme=1.3.0
  - sphinxcontrib-apidoc=0.3.0
  - yapf=0.40.2
  - rdkit=2023.9.4
