name: ms2query
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.18
  - matchms=0.24.1
  - numpy=
  - spec2vec=0.8.0
  - h5py=3.9.0
  - pyarrow=14.0.1
  - tensorflow
  - scikit-learn=1.3.0
  - ms2deepscore=0.4.0
  - pandas=2.0.3
  - matplotlib
  - skl2onnx
  - onnxruntime
  - pytest
  - pytest-cov
  - zip
