name: ms2query
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.18
  - matchms=0.26.4
  - numpy=1.24.4
  - spec2vec=0.8.0
  - h5py=3.11.0
  - pyarrow=16.1.0
  - scikit-learn=1.5.0
  - ms2deepscore=2.0.0
  - pandas=2.2.2
  - matplotlib=3.7.2
  - skl2onnx=1.16.0
  - onnxruntime=1.17.0
  - pytest=8.2.2
  - pytest-cov=5.0.0
  - zip
  - pip
  - pip:
      - torch<2.6
