name: ms2query
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.18
  - matchms=0.24.1
  - numpy=1.24.4
  - spec2vec=0.8.0
  - h5py=3.9.0
  - pyarrow=12.0.1
  - tensorflow=2.12.1
  - scikit-learn=1.3.2
  - ms2deepscore=2.0.0
  - pandas=2.0.3
  - matplotlib=3.7.3
  - skl2onnx=1.16.0
  - onnxruntime=1.16.3
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - zip