name: ms2query
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.18
  - matchms
  - numpy
  - spec2vec
  - h5py=3.9.0
  - pyarrow
  - tensorflow
  - scikit-learn
  - ms2deepscore=0.4.0
  - pandas=2.0.3
  - matplotlib
  - skl2onnx
  - onnxruntime
  - pytest
  - pytest-cov
  - zip
