name: ms2query
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.18
  - matchms=0.24.1
  - numpy
  - spec2vec=0.8.0
  - h5py
  - pyarrow=14.0.2
  - tensorflow
  - scikit-learn=1.3.2
  - ms2deepscore=0.4.0
  - pandas=2.0.3
  - matplotlib=3.7.4
  - skl2onnx=1.16.0
  - onnxruntime=1.15.1
